### ISSUE TITLE
libnormaliz::key_t and size_t are the same on 32bit OS

### ISSUE THREAD

**Issue by sebasguts** [gap-packages/NormalizInterface#24]
When compiling on a 32bit machine, the compiler throws an error, since the functions in line 118 and 124 of normaliz.cc seem to be the same for the compiler. I think this is caused by the fact mentioned in the title.

**Comment by sebasguts** [comment]
Would it be a good idea to only support 64bit architecture?

**Comment by csoeger** [comment]
In libnormaliz I did not have that problem, but that is maybe because there such a function would be templated.
Drop support for 32bit is to early and not necessary.

key_t is a typedef to unsigned int and on that (and probably most) 32 bit architecture size_t also is. But it is not ensured by the standard.

**Comment by sebasguts** [comment]
I got the problem on a debian machine. Maybe it is somehow unique? Unfortunately, I do no longer have access to the computer, but the pull request I made fixed it. But maybe this is to hard?

**Comment by fingolfin** [comment]
Resolved by PR #25
