### ISSUE TITLE
Error in StructuralCopy of NmzCone

### ISSUE THREAD

**Issue by sebasguts** [gap-packages/NormalizInterface#38]
When trying to make a ```StructuralCopy``` of an ```NmzCone```, I get the following error:
```
gap> cone := NmzCone( [ "inequalities", [ [1,0],[0,1] ] ] );
<a Normaliz cone>
gap> StructuralCopy( cone );
Error, Panic: tried to copy object of unknown type '86'
not in any function at line 3 of *stdin*
```
The problem seems to be wrong(?) entries in the ```CopyObjFuncs``` and
```CleanObjFuncs``` arrays. Having the following functions assigned to those
arrays removes the issue, and everything seems to work okay.
```
Obj NormalizCopyFunc(Obj o, Int mut)
{
    return NewCone(GET_CONE<mpz_class>(o));
}

void NormalizCleanFunc(Obj o)
{
}
```
Added by
```
    CopyObjFuncs[ T_NORMALIZ ] = &NormalizCopyFunc;
    CleanObjFuncs[ T_NORMALIZ ] = &NormalizCleanFunc;
```
in the ```InitKernel``` function.

Those functions currently not do what they should do. From
what I got from the source code is that the first one should mark the object
as copied, and return the pointer to the copy if it is called more then once.
So currently the function can (and almost certainly will) produce a memory leak
and issues when asking for equality, but I am not sure how to implement the requirements
for those functions without having extra fields for the pointer to the copy
in the data structure.

On the other hand, this issue is kind of urgent, since it currently prevents
the NmzCone to be set as an attribute in some cases.

**Comment by sebasguts** [comment]
The code is also in d1f2e23

**Comment by sebasguts** [comment]
I just realized that this was a horrible idea. The copy function should look like this:
```
Obj NormalizCopyFunc(Obj o, Int mut)
{
    Cone<mpz_class>* cone= GET_CONE<mpz_class>(o);
    cone = new Cone<mpz_class>(*cone);
    return NewCone(cone);
}
```
But this means that there will be probably made several copys of the cone, where only one should be made. So, any suggestions for the marking and cleaning?

**Comment by fingolfin** [comment]
Hmm, indeed. With your changes applied:
```gap
gap> C := NmzCone(["integral_closure",[[1,2],[3,1]],"grading",[[1,1]]]);
<a Normaliz cone>
gap> l:=[C,C];
[ <a Normaliz cone>, <a Normaliz cone> ]
gap> IsIdenticalObj(l[1],l[2]);
true
gap> k:=StructuralCopy(l);
[ <a Normaliz cone>, <a Normaliz cone> ]
gap> IsIdenticalObj(k[1],k[2]);
false
```

In addition, I am worried about this:
```gap
gap> IsMutable(C);
false
```
So we claim that cone objects are immutable. Normally, that would mean that it is legal to have a copy function which simply returns the object. 

But I think we don't want to consider the cone as immutable... Or do we? I mean, the *cone* as a mathematical object, cannot change anymore after it was created, right? Only what is known about it can change.

So, one point of view is to say: mathematically, cones are immutable, hence never copied, so the copy function just returns the original cone.

Another point of view: cone objects represent the "state of computation", not just the mathematical cone; hence they should be considered mutable, and a copy really should replicate the cone.

@csoeger any thoughts on this?

**Comment by fingolfin** [comment]
To customize the mutability, we need to install something into `IsMutableObjFuncs[ T_NORMALIZ ]`.We may also want to deal with `IsCopyableObjFuncs`, `ShallowCopyObjFuncs`, `MakeImmutableObjFuncs`.

And if we want to support serialization, also `SaveObjFuncs` and `LoadObjFuncs`.

**Comment by fingolfin** [comment]
Note: if we decide cones should be really considered immutable, then `IsCopyable` should return false (look at its documentation to understand why), and then this all probably goes away.

OTOH, if cones are considered to be mutable, then we may have to add logic which implements `MakeImmutable` for them... Though in a quick experiment, it seems we can omit that, then any `MakeImmutable` call invoving an NmzCone simply resulted in  a (non-crashing) error.

**Comment by fingolfin** [comment]
So I can think of two strategies to resolve the copy&clean business:
1. Implement this directly: We then need to store a pointer to the GAP copy of the cone. So we need to reserve two (instead of just one) words when creating the cone object. The second entry would contain the current first entry (i.e. pointer to the C++ object), the first entry would initially be zero.
Then when we are asked to make a copy, we first inspect the first entry; if it is non-zero, it points to the GAP object representing the copy, so we return that. If it is zero, we make a copy, then store a reference to this in entry 1, before returning the copy. Cleaning simply zeroes this entry. And in order to make sure the garbage collector knows about our reference, we must change the `InitMarkFuncBags` argument from `MarkNoSubBags` to `MarkOneSubBags`.

The main drawback of this is that we double the overhead for our wrapper from 8 to 16 bytes. Ah well, nothing to loose sleep about.

2. The alternative would be to only implement this "dumb" kind of copying. But then, never give NmzCone objects directly to the user; instead, always wrap them into a GAP object (positional or component, doesn't matter). (So we'd probably replace occurrences of `NmzCone` by `_NmzCone` or `NmzConeLowLevel`, etc. This means more work at first. But if we used a component object for the wrapper, not only would it take care of the whole "mark for copying" business for us, but also would allow us to e.g. store attributes (the wrapper could be an attribute storing rep).

Anyhow, for now I'd probably go with approach 1, but I wanted to list all options.

**Comment by csoeger** [comment]
> But I think we don't want to consider the cone as immutable... Or do we? I mean, the cone as a mathematical object, cannot change anymore after it was created, right? Only what is known about it can change.

Correct.

> So, one point of view is to say: mathematically, cones are immutable, hence never copied, so the copy function just returns the original cone.
>
> Another point of view: cone objects represent the "state of computation", not just the mathematical cone; hence they should be considered mutable, and a copy really should replicate the cone.

In libnormaliz computing additional data is a non-const operation, since there really the object changes although the represented mathematical object stays the same. For GAP for should use the same approach as for other GAP objects. E.g. is a group immutable? I guess it has also additional data that can be computed later.

**Comment by csoeger** [comment]
So the intended functionality of the copy operation is to create a copy if this object was not copied before and otherwise give the same copy again? And if I create from A a copy B and then from B I could create another copy C, but asking for a copy of A again would give B? Because that is what the first approach would give. Did I get it right?

**Comment by sebasguts** [comment]
@csoeger: A group in GAP is immutable, but attributes in GAP are somehow const functions. They might change the object by adding new information to it, but never change the attributes which are already there, unless some attribute is explicitly declared mutable. I think the normaliz cone somehow mimics this behaviour.

By thinking about the wrapper, I think the conversion from Normaliz to GAP is fast enough to not store all the computed data twice, i.e., in the normaliz cone itself and in the GAP wrapper. So maybe no wrapper is needed. Also, Kamal Saleh is working on using NmzCones in Convex, so there will be some wrapper anyway. We maybe should just make sure that it is complete.

So, when we can have an imutable object and just copy functions that return the same object, I would vote for this. Serialization is another problem, and probably not needed at the moment.

**Comment by csoeger** [comment]
Yes, the libnormaliz cone has a very similar behaviour.

A GAP wrapper object might be the best solution in the long run. Storing the data twice is definitely not worth it, especially since there might be a lot of data that the user never accesses.

At the moment serialisation is not needed and would also be difficult to obtain since the libnormaliz Cone does not support it.

**Comment by sebasguts** [comment]
The duplicated storing would only happen if the user accesses the data, since the wrapper would not request anything from the normaliz object by itself. So there would be only duplication of requested results, so that is not a too large problem.

**Comment by fingolfin** [comment]
There is some confusion here: When I talked about a wrapper, I never meant to say that it should "duplicate" anything. It could, but it doesn't have to. But if it did, then I think for many things it would actually *safe* memory: Right now, if you access cone attribute which is e.g. a matrix, then each time, a new copy of that object is made. So if you write your code carelessly, you can end up with dozens of copies of the same matrix. If the conversion result was stored in an attribute, though, this would not happen.

Anyway, this is besides the point of this issue, I think. 

It seems to me that we all agree that Normaliz cones are mathematically immutable, which matches the definition of "immutable" in GAP. So, we should change the code to flag NmzCone objects as immutable; at which point the copying problem is trivial to resolve: just return the GAP cone object itself as copy.

I'll open a PR for that.
