### ISSUE TITLE
Update the README.md

### ISSUE THREAD

**Issue by HereAround** [gap-packages/NormalizInterface#60]
I am running gap 4.10 on a freshly installed Ubuntu 18.04 and am currently trying to install NormalizInterface. Based on this experience, here are a few suggestions to improve the README.md:

(i) Beyond git, cmake and boost, I also had to install autoconf. Therefore, I would suggest to add autoconf to the list of required software to compile NormalizInterface.
(ii) I installed gap with the standard settings with regards to GMP. Running /build-normaliz.sh GAPDir then resulted in the error

"configure error: GMP C++ library not found Make sure it was compiled with --enable -CXX"

I resolved this by installing the latest version of gmp (sudo apt install libgmp3-dev on Ubuntu 18.04, which I am running). Hence, a suggestion to install the latest version of gmp might be useful.

(iii) ./configure is not there automatically (to my knowledge) but must be created via ./autogen.sh.

**Comment by HereAround** [comment]
The above also refers to the (potentially) outdated version which I pulled from https://github.com/homalg-project/NormalizInterface.git.

**Comment by fingolfin** [comment]
Yeah, please don't use https://github.com/homalg-project/NormalizInterface -- also, several of the points you mention only happened because you used a development version directly from git, not a released version, in particular points (i) and (iii). If you do that, all bets are off, and you are expected to know what you are doing, with all warts.
