### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by antonio-rojas** [gap-packages/NormalizInterface#90]
Building latest git agains normaliz 3.8.3 fails with
```
src/normaliz.cc:349:27: error: ‘boost’ does not name a type
349 | static Obj NmzToGAP(const boost::dynamic_bitset<> & in)
```
Seems there's either a `libnormaliz/dynamic_bitset.h` or a boost include missing.

**Comment by fingolfin** [comment]
@antonio-rojas sorry, I never noticed this issue before :-(

That error is super weird, because normaliz doesn't use boost anymore. For backwards compatibility, we try to still support old normaliz versions which use boost; but we check for `LIBNORMALIZ_DYNAMIC_BITSET_H` to see if this is needed: If LIBNORMALIZ_DYNAMIC_BITSET_H is `#defined` then we don't want to use boost.

The only explanation I can think of here is that you have outdated normaliz headers that are not for Normaliz 3.8 but rather an older version. Can you please check which headers GAP includes, and that they are the correct ones.

**Comment by antonio-rojas** [comment]
But LIBNORMALIZ_DYNAMIC_BITSET_H is defined in libnormaliz/dynamic_bitset.h, which is not included in normaliz.cc. So the check never passes.

**Comment by fingolfin** [comment]
Not true. It is included transitively. Also proven by CI tests passing.

**Comment by antonio-rojas** [comment]
OK tested again with latest git and normaliz 3.8.4 and works now. Must have been an issue with the nomaliz/NormalizInterface combination I was using at the time.

**Comment by fingolfin** [comment]
Awesome! Thanks for taking the time to re-test, and sorry for the looong wait for a reply
